"""Type declarations"""

TRANSACTION_WALLET_CREATION = 1
TRANSACTION_TOKEN_CREATION = 2
TRANSACTION_SMART_CONTRACT = 3
TRANSACTION_TWO_WAY_TRANSFER = 4
TRANSACTION_ONE_WAY_TRANSFER = 5
TRANSACTION_TRUST_SCORE_CHANGE = 6
TRANSACTION_MINER_ADDITION = 7
TRANSACTION_SC_UPDATE = 8
NEWRL_TOKEN_CODE = 'NWRL'
NUSD_TOKEN_CODE = 'NUSD'
NEWRL_TOKEN_NAME = 'Newrl'
NEWRL_TOKEN_DECIMAL = 6
NEWRL_TOKEN_MULTIPLIER = 1000000
NUSD_TOKEN_MULTIPLIER = 1000000

BLOCK_VOTE_VALID = 1  # Valid block by committee members
BLOCK_VOTE_INVALID = 5  # Invalid block and also for proposing an empty block
BLOCK_VOTE_MINER = 9  # Block miner's receipt

BLOCK_STATUS_VALID = 1
BLOCK_STATUS_INVALID_MINED = -1
BLOCK_STATUS_MINING_TIMEOUT = -2
BLOCK_STATUS_CONSENSUS_TIMEOUT = -3

BLOCK_CONSENSUS_VALID = 1
BLOCK_CONSENSUS_INVALID = -1
BLOCK_CONSENSUS_NA = 0