"""Type declarations"""

TRANSACTION_WALLET_CREATION = 1
TRANSACTION_TOKEN_CREATION = 2
TRANSACTION_SMART_CONTRACT = 3
TRANSACTION_TWO_WAY_TRANSFER = 4
TRANSACTION_ONE_WAY_TRANSFER = 5
TRANSACTION_TRUST_SCORE_CHANGE = 6
TRANSACTION_MINER_ADDITION = 7

NEWRL_TOKEN_CODE = 'NWRL'
NUSD_TOKEN_CODE = 'NUSD'
NEWRL_TOKEN_NAME = 'Newrl'
