
GET http://testnet.newrl.net:8182/get-last-block-index
GET http://testnet.newrl.net:8182/get-node-wallet-address
GET http://testnet.newrl.net:8182/get-miners
GET http://testnet.newrl.net:8182/get-peers
GET http://testnet.newrl.net:8182/download-chain
GET http://testnet.newrl.net:8182/download-state
POST http://testnet.newrl.net:8182/run-updater
POST http://testnet.newrl.net:8182/revert-chain?block_index=1&propogate=false

GET http://makemyfund.in:8182/get-last-block-index
GET http://makemyfund.in:8182/get-node-wallet-address
GET http://makemyfund.in:8182/get-miners
GET http://makemyfund.in:8182/get-peers
POST http://makemyfund.in:8182/run-updater
POST http://makemyfund.in:8182/revert-chain?block_index=1&propogate=false

GET http://asqisys.com:8182/get-last-block-index
GET http://asqisys.com:8182/get-node-wallet-address
GET http://asqisys.com:8182/get-miners
GET http://asqisys.com:8182/get-peers
POST http://asqisys.com:8182/run-updater
GET http://asqisys.com:8182/download-chain
POST http://asqisys.com:8182/revert-chain?block_index=1&propogate=false

GET http://localhost:8182/get-last-block-index
GET http://localhost:8182/get-node-wallet-address
GET http://localhost:8182/get-miners
GET http://localhost:8182/get-peers
POST http://localhost:8182/sync-chain-from-peers
POST http://localhost:8182/run-updater
GET http://localhost:8182/download-chain
POST http://localhost:8182/remove-dead-peers
POST http://localhost:8182/revert-chain?block_index=0&propogate=false
POST http://localhost:8182/receive-transaction

{"transaction": {"timestamp": 1648185985420, "trans_code": "8d9817b183d61710c82323c082e9652727931ede", "type": 7, "currency": "NWRL", "fee": 0.0, "descr": "Miner addition", "valid": 1, "specific_data": {"wallet_address": "0x76d5ac405f6885c90c407202c474faff93389605", "network_address": "3.6.169.47", "broadcast_timestamp": 1648185985420}}, "signatures": [{"wallet_address": "0x76d5ac405f6885c90c407202c474faff93389605", "msgsign": "peAZ3HOcQDKDS7EVPEmjMqKMkWJcKLKbK3T1wuphelv7vjQvsYHWUEXOu2quk9O7TJKK/kK+yt6/bYbEAW733g=="}]}

GET http://159.223.163.198:8182/get-last-block-index
GET http://159.223.163.198:8182/get-node-wallet-address
GET http://159.223.163.198:8182/get-miners
GET http://159.223.163.198:8182/get-peers
POST http://159.223.163.198:8182/run-updater
POST http://159.223.163.198:8182/revert-chain?block_index=10&propogate=false
POST http://159.223.163.198:8182/run-updater

POST http://testnet.newrl.net:8182/update-software?propogate=true
POST http://159.223.163.198:8182/update-software?propogate=true
POST http://asqisys.com:8182/update-software?propogate=true
POST http://makemyfund.in:8182/update-software?propogate=false
POST http://localhost:8182/update-software?propogate=true

POST http://159.223.163.198:8182/sync-chain-from-peers

POST http://testnet.newrl.net:8182/revert-chain?block_index=1&propogate=false
POST http://159.223.163.198:8182/revert-chain?block_index=1&propogate=false
POST http://asqisys.com:8182/revert-chain?block_index=1&propogate=false
POST http://makemyfund.in:8182/revert-chain?block_index=1&propogate=false
POST http://localhost:8182/revert-chain?block_index=2230&propogate=false

POST http://testnet.newrl.net:8182/run-updater?add_to_chain_before_consensus=true